---
- name: Ensure old versions of Docker are not installed.
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: Ensure depdencies are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - rsync
    - apt-transport-https
    - ca-certificates

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key

- name: Add Docker repository.
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable"
    filename: docker
    state: present
    update_cache: yes

- name: Install docker.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-compose
    - python-yaml
    - python-docker
