---
- name: Install required packages
  import_tasks: apt.yml

- name: Create docker compose projects path
  file:
    state: directory
    path: "{{ docker_compose_projects_path }}"
    mode: 0700

- name: Ensure rsync is installed
  apt:
    name: rsync
    state: present
