# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "potato" do |p|
    p.vm.box = "generic/debian9"
    p.vm.hostname = "potato"
    p.vm.network :private_network,
        ip: "172.16.1.5",
        netmask: "24",
        virtualbox__intnet: "vpn_link_test"
  end

  config.vm.define "mango" do |m|
    m.vm.box = "generic/debian9"
    m.vm.hostname = "mango"
    m.vm.network :private_network,
        ip: "172.16.1.10",
        netmask: "24",
        virtualbox__intnet: "vpn_link_test"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "../../vpn_link.yml"
    ansible.galaxy_roles_path = "../../roles"
    ansible.raw_arguments = ["-e", "openvpn_host=172.16.1.5"]
    ansible.groups = {
      "vpn_link_server" => ["potato"],
      "vpn_link_client" => ["mango"],
      "vpn_link_server:vars" => {"openvpn_bridge_subnet" => "192.168.168"}
    }
  end
end
