---
- name: Transfer docker-compose project to remote project path
  synchronize:
    src: docker/
    dest: "{{ docker_compose_projects_path }}/dns_server"
    recursive: True
    delete: True

- name: Create bind9 directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/etc/bind/"
    - "/etc/bind/zones/"

- name: Transfer bind9 configuration files
  synchronize:
    src: bind_config/
    dest: /etc/bind/
    recursive: True
    delete: True

- name: Generate named.conf.zones
  copy:
    content: |
      {% for z in zones %}
      zone "{{ z }}" {
        type master;
        file "/etc/bind/zones/db.{{ z }}";
      };
      {% endfor %}
    dest: /etc/bind/zones/named.conf.zones
  vars:
    zones:
      - tolabaki.gr
      - test.tolabaki.gr
      - hwmn.org

- name: Start bind9 docker image
  docker_service:
    project_src: "{{ docker_compose_projects_path }}/dns_server"
    state: present
    restarted: yes
    pull: yes
    build: yes

- name: Ensure dns server is bound on port 53
  wait_for:
    port: 53
    timeout: 20
