---
- name: Install dehydrated and it's dependencies
  import_tasks: installation.yml
  tags:
    - installation

- name: Deploy configuration
  import_tasks: configuration.yml
  tags:
    - configuration

- name: Set up systemd service
  import_tasks: systemd.yml
  tags:
    - systemd
