---
- name: Create systemd timer for dehydrated
  template:
    src: dehydrated.timer.j2
    dest: /etc/systemd/system/dehydrated.timer
  register:
    sd_timer

- name: Create systemd service for dehydrated
  synchronize:
    archive: no
    checksum: yes
    src: dehydrated.service
    dest: /etc/systemd/system/dehydrated.service
  register:
    sd_service

- name: Enable and start systemd timer
  systemd:
    name: dehydrated.timer
    daemon_reload: yes
    enabled: yes
    state: restarted
  when: sd_timer.changed or sd_service.changed
